version: '3'

services:
  postgres:
    build: 
      context: /DB
    ports:
      - "5432:5432"
    networks:
      - library

  Backend:
    build:
      context: /Bookshelf/Backend
    environment:
      - DB_HOST=backend
      - DB_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - "5000:5000"
    networks:
      - library
    depends_on:
      - postgres

  frontend:
    build:
      context: /Bookshelf/frontend
    ports:
      - "3000:3000"
    networks:
      - library
    depends_on:
      - Backend

networks:
  library:
    driver: bridge

